apiVersion: v1
kind: Service
metadata:
  name: flask-app
  namespace: final
  labels:
    app: employees
spec:
  type: Loadbalancer
  ports:
    - protocol: TCP
      name: webapp
      port: 81
      targetport: 81
  Selector:
      app: employees
  
