apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: final
  labels:
    app: employees
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      serviceAccountName: clo835-serviceaccount  # IAM Role for S3 access
      containers:
      - name: flask-container
        image: 383946548058.dkr.ecr.us-east-1.amazonaws.com/app:latest
        ports:
        - containerPort: 81
        env:
        - name: IMAGE_URL
          valueFrom:
            configMapKeyRef:
              name: app-conf
              key: imageurl
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: user
        - name: DBPWD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        - name: DBHOST
          value: :db-service.final.svc.cluster.local"
        - name: DBPORT
          value: "3306"
        -name: DATABASE
          value: "employees"
        - name: AUTHOR_NAME
          valueFrom:
            configMapKeyRef:
              name: app-conf
              key: AUTHOR_NAME
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
              secretKeyRef:
                name: aws-credentials
                key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
              secretKeyRef:
                name: aws-credentials
                key: AWS_SECRET_ACCESS_KEY
         - name: AWS_SECRET_TOKEN
          valueFrom:
              secretKeyRef:
                name: aws-credentials
                key: AWS_SESSION_TOKEN
          - name: ENVIRONMENT
            value: "prod"
    imagePullSecrets:
      - name: creds
    dnsPolicy: ClusterFirst
    restartPolicy: Always
        
        
       
