apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: final
type: Opaque
data:
  MYSQL_USER: bXlzcWwtdXNlcg==  # Base64-encoded 'mysql-user'
  MYSQL_PASSWORD: c2VjdXJlcGFzcw==  # Base64-encoded 'securepass'
